srun: error: gpu31: task 7: Exited with exit code 1
srun: Terminating job step 1562386.0
Traceback (most recent call last):
  File "run_experiments.py", line 42, in <module>
    (args.clients, ips, args.nic, experiment['epochs'], experiment['model'], experiment['batch_size'], experiment['threshold'], experiment['algorithm'], str(clients_distr), experiment['optimizer'], experiment['topology'])
KeyError: 'topology'
Traceback (most recent call last):
  File "run_experiments.py", line 42, in <module>
    (args.clients, ips, args.nic, experiment['epochs'], experiment['model'], experiment['batch_size'], experiment['threshold'], experiment['algorithm'], str(clients_distr), experiment['optimizer'], experiment['topology'])
KeyError: 'topology'
srun: error: gpu26: task 2: Exited with exit code 1
Traceback (most recent call last):
  File "run_experiments.py", line 42, in <module>
    (args.clients, ips, args.nic, experiment['epochs'], experiment['model'], experiment['batch_size'], experiment['threshold'], experiment['algorithm'], str(clients_distr), experiment['optimizer'], experiment['topology'])
KeyError: 'topology'
Traceback (most recent call last):
  File "run_experiments.py", line 42, in <module>
    (args.clients, ips, args.nic, experiment['epochs'], experiment['model'], experiment['batch_size'], experiment['threshold'], experiment['algorithm'], str(clients_distr), experiment['optimizer'], experiment['topology'])
KeyError: 'topology'
Traceback (most recent call last):
  File "run_experiments.py", line 42, in <module>
    (args.clients, ips, args.nic, experiment['epochs'], experiment['model'], experiment['batch_size'], experiment['threshold'], experiment['algorithm'], str(clients_distr), experiment['optimizer'], experiment['topology'])
KeyError: 'topology'
Traceback (most recent call last):
  File "run_experiments.py", line 42, in <module>
    (args.clients, ips, args.nic, experiment['epochs'], experiment['model'], experiment['batch_size'], experiment['threshold'], experiment['algorithm'], str(clients_distr), experiment['optimizer'], experiment['topology'])
KeyError: 'topology'
Traceback (most recent call last):
  File "run_experiments.py", line 42, in <module>
    (args.clients, ips, args.nic, experiment['epochs'], experiment['model'], experiment['batch_size'], experiment['threshold'], experiment['algorithm'], str(clients_distr), experiment['optimizer'], experiment['topology'])
KeyError: 'topology'
Traceback (most recent call last):
  File "run_experiments.py", line 42, in <module>
    (args.clients, ips, args.nic, experiment['epochs'], experiment['model'], experiment['batch_size'], experiment['threshold'], experiment['algorithm'], str(clients_distr), experiment['optimizer'], experiment['topology'])
KeyError: 'topology'
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
srun: error: gpu24: task 0: Exited with exit code 1
srun: error: gpu25: task 1: Exited with exit code 1
srun: error: gpu27: task 3: Exited with exit code 1
srun: error: gpu28: task 4: Exited with exit code 1
srun: error: gpu29: task 5: Exited with exit code 1
srun: error: gpu30: task 6: Exited with exit code 1
